# Generated by Django 4.1.5 on 2023-01-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('stupid_btn', models.IntegerField(default=0)),
                ('fat_btn', models.IntegerField(default=0)),
                ('dumb_btn', models.IntegerField(default=0)),
            ],
        ),
    ]
